/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import com.wnxt.example.vertx.VertexHttpServer;
import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
    @Test public void testAppHasAGreeting() {
        VertexHttpServer classUnderTest = new VertexHttpServer();
        //assertNotNull("app should have a greeting", classUnderTest.getGreeting());
    }
}
